print('Aula 1.6\nDissecando uma variável')
algo=input('Digite algo:')
print('O tipo primitivo desse valor é ', type(algo))
print('É um número?', algo.isnumeric())
print('É alfabético?', algo.isalpha())
print('É alfanumérico?', algo.isalnum())
print('Está em maiúsculas?', algo.isupper())
print('Está em minúsculas?', algo.islower())
print('Só tem espaços?', algo.isspace())
print('Está capitalizada?{}'.format(algo.istitle()))

